---
vnc_desktop: gnome
   - username: 'ubuntu'
     usergroup: 'ubuntu'     # usergroup is optional. Defaults to username.
     #port 5901 is 1
     vnc_num: 1
     vnc_default_password: mypassword

vnc_desktop: gnome
#########################
# Used with older vnc servers.
vnc_server_options: "-geometry 1920x1200 -localhost"

# Used by this role on newer tiger vnc servers.
vnc_config_options:
  - "geometry=1920x1200"
  - "localhost"

### Should the role generate and enable per-user systemd services for VNC desktops?
### This variable refers to a previous implementation of per-user systemd, before the newer TigerVNC update, where standard systemd is used.
vnc_install_systemd_services: false

### Add the vncstart.sh script to users' .bashrc for vnc autostart when logging in? Recommended.
vnc_bashrc_startup: true

### Ansible will create certain scripts such as ~/.config/systemd/user/vncserver.service and ~/vncstart.sh
### The question is should Ansible overwrite them later on? Set this to True or False.
vnc_ansible_managed_startup_scripts: false

### Ansible will create xstartup. The question is should Ansible overwrite xstartup files later on? Set this to True or False.
vnc_ansible_managed_xstartup: false

### Ansible will create .vnc/config. The question is should Ansible overwrite .vnc/config later on? Set this to True or False.
vnc_ansible_managed_config: false

### It has been discovered that an Ubuntu server, in the Cloud, ought to be rebooted at least one time in order to fix the locale settings.
### If you set this to True, then Ansible will reboot the server. The default here is False, so you will need to reboot manually.
### Only affected the older per-user systemd configurations.
vnc_reboot_once: false
#########################
# This is a role for setting up the client.

- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Install packages
  apt:
    pkg:
     - nmap
     - hydra
     - medusa
    update_cache: yes

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/user/passlist.txt
    owner: user
    mode: 0644

...
